#!/bin/bash

BASE_DIR_SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

if [[ "$1" == "configure" ]]; then
    $BASE_DIR_SCRIPT/bigButton_launcher
if [[ "$1" == "configure" ]]; then
    $BASE_DIR_SCRIPT/configurator
elif [[ "$1" == "uninstall" ]]; then
    read -n 1 -p "Do you want to uninstall the script ? [y/n] `echo $'\n> '`" resp
    echo 
    if [[ "$resp" == "y" ]]; then
        echo "Start uninstallation..."
        echo 
        $BASE_DIR_SCRIPT/uninstall.sh
    else    
        echo "uninstallation aborted"
        exit 0
    fi
else
    echo "bigButton <command>"
    echo " command : "
    echo "   configure"
    echo "   uninstall"
    echo "   start"
fi

exit 0
