#!/bin/bash

BASE_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

source "$BASE_SCRIPT_DIR/helpers"

flock -e --nonblock $BASE_DIR/$MAIN_LOCKFILE_NAME $BASE_DIR/main || echo "An instance of the script is already running"
