#!/bin/bash

BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

LOCKDIR="/tmp/big-button-lockfile"

if mkdir $LOCKDIR
then
    #exclusive lock

    $BASE_DIR/main

    if rmdir $LOCKDIR
    then
        exit 0
    else
        log "error" "Could not remove lock for main bash instance"
        exit -1
    fi
else
    echo "An instance of the script is already running"
    exit -1
fi

