#!/bin/bash

source $HELPERS_SCRIPT

DEVICE_PATH=$1

if [[ -z $DEVICE_PATH ]]; then
    echo "No device path given"
    exit -1
fi

DEVICE_NAME=$(basename "$DEVICE_PATH")
PIPE="/dev/$DEVICE_NAME"

#empty previous resting data
echo "" > $PIPE

#start reading
cat $PIPE | 
while read -r line
do
    if [[ "$line" == "ready" ]]; then
        executeScriptsInDir  "$EVENTS_DIR/device/ready"
    elif [[ "$line" == "up" ]]; then
        executeScriptsInDir  "$EVENTS_DIR/button/up"
    elif [[ "$line" == "down" ]]; then
        executeScriptsInDir  "$EVENTS_DIR/button/down"
    fi
done
